language: go
go:
  - 1.17.x
install:
  - go get -v golang.org/x/lint/golint
  - go mod tidy -v
script:
  - golint -set_exit_status ./...
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip